name = "linverge-website"
main = "worker.js"
compatibility_date = "2026-05-07"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

workers_dev = false
domains = ["linverge.com", "www.linverge.com", "rs.linverge.com"]

[assets]
directory = "."
not_found_handling = "single-page-application"
